"""generic

Revision ID: 94ad92651926
Revises: 
Create Date: 2025-12-30 01:38:02.352666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94ad92651926'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('career_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.JSON(), nullable=False),
    sa.Column('rank_required', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('parent_node_id', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['parent_node_id'], ['career_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('job_role', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_stage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('resume_analysis', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_applications_id'), 'interview_applications', ['id'], unique=False)
    op.create_index(op.f('ix_interview_applications_user_id'), 'interview_applications', ['user_id'], unique=False)
    op.create_table('user_progress',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('current_xp', sa.Integer(), nullable=True),
    sa.Column('daily_streak', sa.Integer(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('skill_stats', sa.JSON(), nullable=True),
    sa.Column('target_role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('interview_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('stage_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('candidate_name', sa.String(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('feedback_markdown', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['interview_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_application_id'), 'interview_sessions', ['application_id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_id'), 'interview_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_session_id'), 'interview_sessions', ['session_id'], unique=True)
    op.create_table('user_achievements',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('achievement_id', sa.String(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_progress.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'achievement_id')
    )
    op.create_table('user_nodes',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('high_score', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['career_nodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_progress.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'node_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_nodes')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_interview_sessions_session_id'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_id'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_application_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_interview_applications_user_id'), table_name='interview_applications')
    op.drop_index(op.f('ix_interview_applications_id'), table_name='interview_applications')
    op.drop_table('interview_applications')
    op.drop_table('career_nodes')
    op.drop_table('achievements')
    # ### end Alembic commands ###
